name: CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'SqlServerMcp/**'
      - '*.sln'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    uses: ./.github/workflows/build.yml
    with:
      dotnet-version: '8.0.x'
      configuration: 'Release'

  lint:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # GitVersion needs full history

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SqlServerMcp.sln

      - name: Format check
        run: dotnet format SqlServerMcp.sln --verify-no-changes --verbosity diagnostic

      - name: Analyze
        run: dotnet build SqlServerMcp.sln --configuration Release /p:TreatWarningsAsErrors=true

  publish:
    name: Publish to NuGet
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # GitVersion needs full history

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Pack NuGet package
        run: dotnet pack SqlServerMcp/SqlServerMcp.csproj --configuration Release --output ./packages

      - name: Push to NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
