name: Pull Request

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'SqlServerMcp/**'
      - '*.sln'
      - '.github/workflows/**'

jobs:
  build:
    name: Build and Test
    uses: ./.github/workflows/build.yml
    with:
      dotnet-version: '8.0.x'
      configuration: 'Debug'

  lint:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # GitVersion needs full history

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SqlServerMcp.sln

      - name: Format check
        run: dotnet format SqlServerMcp.sln --verify-no-changes --verbosity diagnostic

      - name: Build with warnings as errors
        run: dotnet build SqlServerMcp.sln --configuration Debug /p:TreatWarningsAsErrors=true

  size-check:
    name: Binary Size Check
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # GitVersion needs full history

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish SqlServerMcp/SqlServerMcp.csproj --configuration Release --output ./publish

      - name: Check binary size
        run: |
          SIZE=$(du -sb ./publish | cut -f1)
          SIZE_MB=$(echo "scale=2; $SIZE / 1024 / 1024" | bc)
          echo "Published size: ${SIZE_MB} MB"
          echo "::notice::Published binary size is ${SIZE_MB} MB"
